---
title: "Untitled"
output: html_document
date: "2024-04-18"
---

Primer ejemplo
```{r}
verde=c(8,8.5,8,11.5,11,10,9,9.5,9,10)
azul=c(5,5.5,5,5.2,4.8,5.8,5,5.5,5.3,4.9)
rojo=c(4,4.5,4,7.5,7,6,5,5.5,5,5)
predic=seq(1,10,by=1)

x= rbind(verde,rojo,azul)
dim(x)
round(cor(t(x)),2)
plot(predic,x[1,],type = "l",col="green", ylim = c(0, 12),main = "ejemplo1",ylab = "")
lines(predic, x[2,], type = "l", col = "red")
lines(predic, x[3,], type = "l", col = "blue")

#Ejemplo 2
x1=x
x1[1,10]=15
x1
dim(x1)
1-round(cor(t(x1)),2) #distancias

plot(predic,x1[1,],type = "l",col="green", ylim = c(0, 12),main = "ejemplo2",ylab = "")
lines(predic, x1[2,], type = "l", col = "red")
lines(predic, x1[3,], type = "l", col = "blue")
```

```{r}
# Lo ultimo que hicimos
x2=t(x1)
d=matrix(data=0,nrow = 3,ncol = 3)
for (i in 1:10) {
  base= x2[-i,]
d=d+(1-cor(base))
}
d/10
```
##Clase 

```{r}
options(digits = 5)
base1=base[,c(19,20,21,22,24)]
base2=base1[1:10,]

d=dist(base1)

dm=as.matrix(d);d

b=dm[5:10,1:4]
min(b);max(b);mean(b)

base3=rbind(base2[c(1,4,7,9,10),],base2[c(2,3,5,6,8),])

d1=dist(base3);d1
dm1=as.matrix(d1);dm1

b1=dm1[6:10,1:5]
b1

min(b1);max(b1);mean(b1)
```

```{r}
base4=base2[c(1,4,7,9,10),]
base5=base2[c(2,3,5,6,8),]


g1=apply(base4, 2, mean)## Centroides
g2=apply(base5, 2, mean)
g3=g1-g2

sqrt(t(g3)%*%g3)
```

```{r}


cs=hclust(d,method = "single")
cs

plot(cs)
```

```{r}
cs=hclust(d,method = "complete")
cs

plot(cs)
```

```{r}
cs=hclust(dist(base1,method = "manhattan"),method = "single")
cs

plot(cs)
```

```{r}
cs=hclust(dist(base2),method = "ward.D")
cs

plot(cs)

dist(base2)
```



## ACTIVIDAD 1 presentaciones

```{r}
load("datoscor.Rdata")
```

Person 
```{r}
A[1,1]= 7000 #valor extremo
pers = 1- round(cor(t(A)),4)
d.pers =as.dist(pers) ; d.pers
```

Euclidea
```{r}
d.eu=dist(A,method = "euclidean") ;round(d.eu,3)
```

Jacknife
```{r}
x2=t(A)
d=matrix(data=0,nrow = 10,ncol = 10)
for (i in 1:10) {
  base= x2[-i,]
d=d+(1-cor(base))
}
d.jack=as.dist(d/10);d.jack
```

```{r}
predic=seq(1,6,by=1)
plot(predic, A[1,],type = "l",col="green", ylim = c(0, 10000),main = "Individuos",ylab = "")
lines(predic, A[2,], type = "l", col = "red")
lines(predic, A[3,], type = "l", col = "blue")
lines(predic, A[4,], type = "l", col = "blue")
lines(predic, A[6,], type = "l", col = "blue")
lines(predic, A[7,], type = "l", col = "blue")
lines(predic, A[8,], type = "l", col = "blue")
lines(predic, A[9,], type = "l", col = "blue")
lines(predic, A[10,], type = "l", col ="blue")
```

```{r}
round(d.eu,3)
round(d.jack,3)
round(d.pers,3)
```

