---
title: "Untitled"
output: html_document
date: "2024-05-06"
---

## ACTIVIDAD 1 presentaciones

```{r}
load("datoscor.Rdata")
```

Person 
```{r}
A[1,1]= 7000 #valor extremo
pers = 1- cor(t(A))
d.pers =as.dist(pers) ; d.pers
```

Euclidea
```{r}
d.eu=dist(A,method = "euclidean") ;round(d.eu,3)
```

Jacknife
```{r}
x2=t(A)
d=matrix(data=0,nrow = 10,ncol = 10)
for (i in 1:10) {
  base= x2[-i,]
d=d+(1-cor(base))
}
d.jack=as.dist(d/10);d.jack
```

```{r}
predic=seq(1,6,by=1)
plot(predic, A[1,],type = "l",col="green", ylim = c(-1000, 10000),main = "Individuos",ylab = "")
lines(predic, A[2,], type = "l", col = "blue")
lines(predic, A[3,], type = "l", col = "blue")
lines(predic, A[4,], type = "l", col = "blue")
lines(predic, A[6,], type = "l", col = "blue")
lines(predic, A[7,], type = "l", col = "blue")
lines(predic, A[8,], type = "l", col = "blue")
lines(predic, A[9,], type = "l", col = "blue")
lines(predic, A[10,], type = "l", col ="blue")
```
```{r}
round(d.eu,3)
round(d.jack,3)
round(d.pers,3)
```