---
title: "Untitled"
output: html_document
date: "2024-04-16"
---

```{r}
# Carga del conjunto de datos iris
data(iris)

# Visualización de las primeras filas del conjunto de datos
head(iris)

# Aplicación del PCA al conjunto de datos iris
pca_result <- prcomp(iris[, -5], scale. = TRUE)

# Resumen del resultado del PCA
summary(pca_result)

# Gráfica de la varianza explicada por cada componente principal
plot(pca_result, type = "l")

# Gráfica de la dispersión de las observaciones en el primer y segundo componente principal
plot(pca_result$x[,1], pca_result$x[,2], col = iris$Species, 
     xlab = "Primer Componente Principal", ylab = "Segundo Componente Principal",
     main = "PCA de conjunto de datos iris")

# Agregar etiquetas para las especies
legend("topright", legend = levels(iris$Species), col = 1:3, pch = 1)

```
```{r}
# Carga del conjunto de datos mtcars
data(mtcars)

# Visualización de las primeras filas del conjunto de datos
head(mtcars)

# Aplicación del PCA al conjunto de datos mtcars
pca_result <- prcomp(mtcars[, -c(1:4)], scale. = TRUE)

# Resumen del resultado del PCA
summary(pca_result)

# Gráfica de la varianza explicada por cada componente principal
plot(pca_result, type = "l")

# Gráfica de la dispersión de las observaciones en el primer y segundo componente principal
plot(pca_result$x[,1], pca_result$x[,2], col = "blue", 
     xlab = "Primer Componente Principal", ylab = "Segundo Componente Principal",
     main = "PCA de conjunto de datos mtcars")

# Etiquetar cada punto con el nombre del modelo de automóvil
text(pca_result$x[,1], pca_result$x[,2], rownames(mtcars), pos = 3, col = "red")
```

