# 8.2 Manzanas
Las manzanas tienen un compuesto llamado polifenol oxidasa, el cual hace que al
cortarse y entrar en contacto con el aire se oscurezcan rápidamente. Para evitar el
pardeamiento se probaron tres tratamientos: tapar (código 2), poner en bolsa plástica
cerrada (código 3), y aplicar jugo de limón (código 4). Además, se incluyó un control
sin aplicar nada (código 1). Una vez aplicados los tratamientos el resultado fue
evaluado por 10 jueces que calificaron el color en una escala de 1 a 6 donde 1 es
el color normal de la fruta y 6 es el más oscuro. El objetivo final es seleccionar el
tratamiento que mantenga mejor el color original para una empresa que se encarga
de banquetes.

8.2.1 Ejercicios
#1. Potencia:
##(a) Tomando como base los datos de las manzanas.
i. Observe los promedios muestrales para los 4 tratamientos.
ii. Obtenga la estimación de la variancia del error.

##(b) Cree una función llamada med que devuelva la probabilidad en el anova
de datos generados. Esta función debe tener como argumentos: el número
de réplicas por tratamiento (r), un vector de medias verdaderas (mu) y
la variancia del error (v), la cual se declara por default en 1. La función
debe crear el vector del tratamiento según el número de réplicas y niveles
que tenga el factor, además debe crear la respuesta según el modelo que
parte de esas medias verdaderas con un error normal con media cero y la
variancia que se le da.

##(c) Vamos a suponer que para el investigador dos promedios empiezan a
considerarse realmente diferentes si tienen una diferencia de dos puntos
(δ = 2). Vamos a imaginar que se conocen las medias verdaderas y que se
cumple con que dos de ellas se diferencian en dos puntos, por lo que sería
importante que al hacer el experimento se pueda concluir que no todas
las medias son iguales, es decir, sería lo más deseable que se rechace la
hipótesis de igualdad de medias. Se quiere simular la extracción de datos
1000 veces, y cada vez obtener la probabilidad asociada a la hipótesis de
igualdad de medias. Se procede de la siguiente forma:

i. Use los siguientes valores para las verdaderas medias: 3, 3, 2 y 4.
Coloque los valores de esas medias en un vector llamado mu1.

ii. Use un tamaño de muestra r=5. Además use el valor de default
para la variancia del error, es decir, v=1. Haga una secuencia de 1000
iteraciones donde cada vez se haga la simulación. Cree primero un
vector vacío donde va a ir almacenando la probabilidad asociada en
cada iteración. Haga un ciclo con 1000 iteraciones, en cada una de esas
iteraciones llame la función med y coloque el resultado en la posición
correspondiente del vector de probabilidades.

iii. Obtenga la proporción de veces que se rechaza la hipótesis nula. Esta
proporción representa qué tan fácil es ver las diferencias si en realidad
existen y se llama potencia.

## (d) Una forma de obtener la potencia directamente en R es usando la función
power.anova.test de la librería pwr. Debe indicarse el número de grupos,
el número de observaciones por grupo que en este caso se le llama n, debe
darse la variancia de las medias hipotéticas en el argumento between.var
y la variancia del error en el argumento within.var. Se usa de la siguiente
forma: power.anova.test(n=5,groups=4,between.var=var(mu1),
within.var=1).
## (e) Compare este resultado con el obtenido en la simulación.

# 2. Número de réplicas:

## (a) Si se quiere que haya una probabilidad de 0,90 de rechazar la hipótesis
cuando existen diferencias de al menos dos puntos entre medias, se calcula
el tamaño de muestra necesario con la misma función pero no se pone el
n y se especifica la potencia en el parámetro power. Para extraer el tamaño
de muestra se usa $n y para extraer la potencia se usa $power.

## (b) En la práctica no se conoce el verdadero valor de la variancia del error,
entonces se usa su estimación que es el cuadrado medio residual. Además
para el parámetro between.var existen infinitas combinaciones de las
posibles medias verdaderas, algo que el investigador no conoce. Entoces
se puede probar con diferentes valores intermedios en el vector mu1. Haga
diferentes pruebas y determine en qué caso se obtiene el mayor número de
réplicas y en qué caso el menor número de réplicas.
