---
title: "Mariposas"
author: "Génesis Villalobos Salas"
date: "2023-05-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

mariposas2 <- read.csv("C:/Users/DELL/Dropbox/Experimentos I - 2023/Prácticas/Mariposas2.csv", sep=";")
names(mariposas2)

mariposas2$sitio = as.factor(mariposas2$sitio)
mariposas2$semana = as.factor(mariposas2$semana)
mariposas2$bloque= interaction(mariposas2$sitio,mariposas2$semana)
mariposas2$bloque=  as.factor(mariposas2$bloque)

```

```{r}
mod= lm(frec~especie+altura+especie*altura+ bloque, data= mariposas2)
anova(mod)
fb= anova(mod)[5,1]
fa= anova(mod)[5,1]+anova(mod)[3,1]
cmbloque = anova(mod)[3,3]
cmres = anova(mod)[5,3]
```
Eficiencia Relativa 

```{r}
b= 16
n= nrow(mariposas2)
  
cmresda=  ((b-1)*cmbloque+(n-b)*cmres)/(n-1) #Aqui la formula cambia porque tenemos 2 factores entonces a ya no sera la cantidad de niveles de factor. Entonces b= cantidad de bloques, n cantidad de observaciones. contrario a la de un solo factor.

eer= ((fb+1)*(fa+3)*cmresda)/ ((fb+3)*(fa+1)*cmres)
```

