8.3 Tortugas
Se desea determinar si la falta de alimento afecta el nivel de proteínas en sangre en
tortugas. En el primer caso se tienen tortugas de la especie Chelonia midas de ambos
géneros (machos y hembras), con dos condiciones: 1) dieta regulada y 2) alimento
en abundancia, mientras que en el segundo caso se tiene tortugas de dos especies:
Kinosternum scorpioides y Chelonia midas, con tres condiciones: 1) dieta estricta,
2) dieta balanceada y 3) alimento en abundancia. Se registra el nivel de proteína en
gramos por decilitro (gr/dl).

#8.3.1 Ejercicios
1. Dos factores sin interacción: tome como base los datos del archivo
tortugas1.csv, en el cual se tienen dos factores. En el análisis previo se verificó
que no hay interacción entre condición de alimento y género. Aunque se tienen
4 tratamientos, cualquier comparación se hace solo entre dos niveles, sea entre
los dos niveles de alimento o entre los dos niveles de género. En este caso
particular lo que se desea comparar son los promedios de proteína para los
dos niveles de alimento. Para calcular la potencia de este experimento se debe
tomar en cuenta la cantidad de réplicas que se tienen en cada nivel de alimento
sin importar el género.
## (a) Obtenga el número de réplicas por condición de alimento.
## (b) Obtenga la estimación de la variancia del error.
## (c) Suponga que una diferencia de 2 gr/dl en el promedio de proteína ya
es relevante para el investigador. Calcule la potencia que se tiene en este
experimento de detectar esa diferencia si la hubiera.
## (d) ¿Cuántas réplicas se recomendaría utilizar para que la potencia de detectar
diferencias de 2 gr/dl sea de 0,90?
## (e) Calcule el límite inferior para la diferencia entre el promedio de proteínas
con alimento en abundancia con respecto a dieta. Use las medias
observadas.
## (f) Se ha observado que no se ha llegado a una conclusión muy clara sobre el
efecto real de la condición de dieta. Por otra parte se sugiere una muestra
mucho más grande para llegar a detectar diferencias de la magnitud que
se estableció. Si se repite el experimento con 38 tortugas por condición, ¿se
asegura que el límite inferior supere los 2 gr/dl?

2. Dos factores con interacción: tome como base los datos del archivo
tortugas2.csv, en el cual se también se tienen dos factores. En el análisis previo
se verificó que sí hay interacción entre condición de alimento y especie, por lo
tanto las comparaciones entre promedios según condición se deben hacer para
cada especie por separado. Para calcular la potencia de este experimento se
debe tomar en cuenta la cantidad de réplicas que se tienen en cada nivel de
alimento dentro de cada especie.
## (a) Obtenga el número de réplicas por condición de alimento y especie.
## (b) Obtenga la estimación de la variancia del error.
## (c) Calcule la potencia que se tiene en este experimento de detectar una
diferencia de 2 gr/dl en los promedios de proteína si la hubiera.
## (d) En un laboratorio anterior se calcularon los límites inferiores para las
diferencias de medias que resultaron significativas. En particular para
chelonia se concluyó que con 95% de confianza el nivel promedio de
proteína es al menos 7,29 gr/dl con dieta balanceada que con dieta estricta.
¿Por qué si este experimento tiene tan baja potencia se logró llegar a un
límite tan alto con tan pocas réplicas para hacer las comparaciones?
## (e) Verifique cuál sería el tamaño de muestra mínimo por tratamiento si se
quisiera tener una potencia de 0,95 para detectar diferencias mayores a 7
gr/dl.
